TrajectoryPlannerROS:
  max_vel_x: 0.1
  min_vel_x: 0.05
  max_vel_theta: 0.6
  min_in_place_vel_theta: 0.4
  acc_lim_theta: 0.2
  acc_lim_x: 0.01
  holonomic_robot: true
  #yaw_goal_tolerance: 0.08
  #xy_goal_tolerance: 0.2

