TrajectoryPlannerROS:
  max_vel_x: 0.50
  min_vel_x: 0.10
  max_vel_theta: 1.4
  min_vel_theta: 0.6
  min_in_place_vel_theta: 1.0 
  #MAX THETA 1.6
  acc_lim_theta: 0.1
  acc_lim_x: 0.1
  holonomic_robot: true
  yaw_goal_tolerance: 0.7
  #xy_goal_tolerance: 0.2
  sim_time: 2
  controller_frequency: 10

