#Common File For Costmap2D

obstacle_range : 1.5
raytrace_range : 2.5 

footprint: [[0.25,0.25], [0.25,-0.25], [-0.25,-0.25], [-0.25,0.25]]
#footprint: [[0.25,0.25], [0.25,-0.25], [-0.25,-0.25], [-0.25,0.25]]

inflation_radius: 0.30
#0.35

observation_sources: scan 
#, point_cloud_sensor


scan: {sensor_frame: /laser, data_type: LaserScan, topic: /scan_filtered, marking: true, clearing: true, expected_update_rate: 10}
#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
