#Common File For Costmap2D
obstacle_range: 2.0
raytrace_range: 3.0

footprint: [[0.3,0.3], [0.3,-0.3], [-0.3,-0.3], [-0.3,0.3]]

inflation_radius: 0.55

observation_sources: scan

scan: {sensor_frame: /laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 10}

